// Generated by CoffeeScript 1.9.2
(function() {
  var app;

  app = angular.module('wedding', ['ngRoute', 'ngMaterial']);

  app.config([
    '$routeProvider', function($routeProvider) {
      return $routeProvider.when('/wedding', {
        templateUrl: 'views/index'
      }).otherwise({
        redirectTo: '/index'
      });
    }
  ]);

  app.controller('weddingCtrl', [
    '$scope', '$http', function($scope, $http) {
      return $scope.gggg = function() {
        console.log('gggg');
        return $http.get('../api/sendEmail');
      };
    }
  ]);

}).call(this);
