// Generated by CoffeeScript 1.9.2
(function() {
  var app;

  app = angular.module('hutCrawler', ['ngRoute']);

  app.config([
    '$routeProvider', function($routeProvider) {
      return $routeProvider.when('/huts', {
        templateUrl: 'views/huts'
      }).when('/about', {
        templateUrl: 'views/about'
      }).when('/question', {
        templateUrl: 'views/question'
      }).when('/contact', {
        templateUrl: 'views/contact'
      }).otherwise({
        redirectTo: '/huts'
      });
    }
  ]);

  app.controller('hutCrawlerCtrl', [
    '$scope', '$http', function($scope, $http) {
      $scope.isLoading = true;
      $scope.hutGroups = [];
      $scope.topBarHutNames = [];
      $scope.hutNameZhSelected = '';
      $scope.titleBarNameSelected = '台灣山屋餘額查詢';
      $scope.calendarTitles = [];
      $scope.adminColor = {
        '0': 'adminColorEven',
        '1': 'adminColorOdd'
      };
      $scope.titleBar = [
        {
          url: '#/contact',
          name: '聯絡我'
        }, {
          url: '#/question',
          name: '常見問題'
        }, {
          url: '#/huts',
          name: '台灣山屋餘額查詢'
        }, {
          url: '#/about',
          name: '關於'
        }
      ];
      $http.get('/api/hut').success(function(result, statusCode) {
        $scope.isLoading = false;
        $scope.hutGroups = result.hutGroups;
        return $scope.huts = result.huts;
      }).error(function(e) {
        return console.log(e);
      });
      $scope.hutNameClicked = function(hutNameZh) {
        var day, hut, hutApplicableAll, hutApplicableInOneWeek, i, istatus, j, k, len, len1, ref, ref1, ref2, results, status;
        $scope.calendarTitles = ['日', '一', '二', '三', '四', '五', '六'];
        $scope.hutNameZhSelected = hutNameZh;
        hutApplicableAll = [];
        hutApplicableInOneWeek = [];
        ref = $scope.huts;
        results = [];
        for (i = 0, len = ref.length; i < len; i++) {
          hut = ref[i];
          if (hut.nameZh === hutNameZh) {
            ref1 = hut.capacityStatuses.status;
            for (istatus = j = 0, len1 = ref1.length; j < len1; istatus = ++j) {
              status = ref1[istatus];
              day = new Date(status.date).getDay();
              if (istatus === 0 && day !== 0) {
                for (k = 0, ref2 = day; 0 <= ref2 ? k < ref2 : k > ref2; 0 <= ref2 ? k++ : k--) {
                  hutApplicableInOneWeek.push({});
                }
              }
              hutApplicableInOneWeek.push(status);
              if (istatus === hut.capacityStatuses.status.length - 1 || day === 6) {
                hutApplicableAll.push(hutApplicableInOneWeek);
                hutApplicableInOneWeek = [];
              }
            }
            $scope.hutApplicableAll = hutApplicableAll;
            break;
          } else {
            results.push(void 0);
          }
        }
        return results;
      };
      return $scope.titleBarNameClicked = function(titleBarName) {
        return $scope.titleBarNameSelected = titleBarName;
      };
    }
  ]);

}).call(this);
