// Generated by CoffeeScript 1.9.2
(function() {
  var async, cheerio, moment, request, url;

  async = require('async');

  moment = require('moment');

  request = require('request');

  cheerio = require('cheerio');

  console.log(moment().add(7, 'd').format());

  url = 'https://mountain.ysnp.gov.tw/chinese/LocationAppIndex.aspx?pg=01&w=1&n=1003';

  request(url, function(err, res, body) {
    var $, a, cookie;
    cookie = res.headers['set-cookie'][0].split(';')[0];
    $ = cheerio.load(body);
    return a = request({
      'method': 'POST',
      'url': url,
      'headers': {
        'Cookie': cookie
      },
      'form': {
        'ctl00_ContentPlaceHolder1_ToolkitScriptManager1_HiddenField': '',
        '__EVENTTARGET': 'ctl00$ContentPlaceHolder1$gvIndex$ctl13$txtPageSize',
        '__EVENTARGUMENT': $('#__EVENTARGUMENT').val(),
        '__VIEWSTATE': $('#__VIEWSTATE').val(),
        '__VIEWSTATEGENERATOR': $('#__VIEWSTATEGENERATOR').val(),
        '__VIEWSTATEENCRYPTED': $('#__VIEWSTATEENCRYPTED').val(),
        '__EVENTVALIDATION': $('#__EVENTVALIDATION').val(),
        'ctl00$ContentPlaceHolder1$txtSDate': '2015/05/16',
        'ctl00$ContentPlaceHolder1$ddlLocation': 1,
        'ctl00$ContentPlaceHolder1$btnSearch.x': 32,
        'ctl00$ContentPlaceHolder1$btnSearch.y': 5,
        'ctl00$ContentPlaceHolder1$gvIndex$ctl23$txtPageSize': 50
      }
    }, function(err, res, body) {
      console.log(res.statusCode);
      $ = cheerio.load(body);
      return console.log($('#ctl00_ContentPlaceHolder1_gvIndex tr').length - 3);
    });
  });

}).call(this);
