// Generated by CoffeeScript 1.9.2
(function() {
  var async, cheerio, moment, month1, month2, request, timeStartCrawling, url, url1, url2, year;

  async = require('async');

  moment = require('moment');

  request = require('request');

  cheerio = require('cheerio');

  url = 'http://tconline.forest.gov.tw/order/';

  timeStartCrawling = moment();

  console.log(moment().add(7, 'd').format('YYYY/MM/DD'));

  console.log(moment().add(45, 'd').format('YYYY/MM/DD'));

  year = moment().year();

  month1 = ('0' + (moment().month() + 1)).slice(-2);

  month2 = ('0' + (moment().month() + 2)).slice(-2);

  url1 = 'http://tconline.forest.gov.tw/order/?year=' + year + '&month=' + month1;

  url2 = 'http://tconline.forest.gov.tw/order/?year=' + year + '&month=' + month2;

}).call(this);
