// Generated by CoffeeScript 1.9.2
(function() {
  var async, cheerio, parser, request;

  request = require('request');

  cheerio = require('cheerio');

  async = require('async');

  async.waterfall([
    function(cb) {
      return request('http://recreation.forest.gov.tw/index.aspx', function(err, res, body) {
        var $;
        $ = cheerio.load(body);
        return cb(null, $('#__VIEWSTATE').val(), $('#__EVENTVALIDATION').val());
      });
    }, function(viewstate, eventvalidation, cb) {
      return request({
        'method': 'POST',
        'url': 'http://recreation.forest.gov.tw/index.aspx',
        'headers': {
          'Connection': 'keep-alive'
        },
        'form': {
          '__VIEWSTATE': viewstate,
          '__EVENTVALIDATION': eventvalidation,
          'ctl00$ContentPlaceHolder1$ID_TextBox': 'hut.crawler.tw@gmail.com',
          'ctl00$ContentPlaceHolder1$Pass_TextBox': 'iamahutcrawler1',
          'ctl00$ContentPlaceHolder1$btn_login': '登入'
        }
      }, function(err, res, body) {
        var cookie;
        cookie = res.headers['set-cookie'][0].split(';')[0];
        return cb(null, cookie);
      });
    }, function(cookie, cb) {
      return request({
        'url': 'http://recreation.forest.gov.tw/askformonhouse/AskForPaperAddNew.aspx?mode=0&AskSID=&houseid=C',
        'headers': {
          'Connection': 'keep-alive',
          'Cookie': cookie
        }
      }, function(err, res, body) {
        var $;
        $ = cheerio.load(body);
        parser($);
        return cb(null, cookie, $('#__VIEWSTATE').val(), $('#__EVENTVALIDATION').val());
      });
    }, function(cookie, viewstate, eventvalidation, cb) {
      return request({
        'method': 'POST',
        'url': 'http://recreation.forest.gov.tw/askformonhouse/AskForPaperAddNew.aspx?mode=0&AskSID=&houseid=C',
        'headers': {
          'Cookie': cookie
        },
        'form': {
          '__VIEWSTATE': viewstate,
          '__EVENTVALIDATION': eventvalidation,
          '__EVENTTARGET': 'eventscalendar$ctl00$NextMonth',
          '__VIEWSTATEENCRYPTED': ''
        }
      }, function(err, res, body) {
        var $;
        $ = cheerio.load(body);
        parser($);
        return cb(null, 'done');
      });
    }
  ], function(err, result) {
    return console.log(result);
  });

  parser = function($) {
    var capacityStatus, dayPre, month, monthZH;
    monthZH = $('#eventscalendar_ctl00_label2').text().split(' ')[0];
    month = 0;
    switch (monthZH) {
      case '一月':
        month = 1;
        break;
      case '二月':
        month = 2;
        break;
      case '三月':
        month = 3;
        break;
      case '四月':
        month = 4;
        break;
      case '五月':
        month = 5;
        break;
      case '六月':
        month = 6;
        break;
      case '七月':
        month = 7;
        break;
      case '八月':
        month = 8;
        break;
      case '九月':
        month = 9;
        break;
      case '十月':
        month = 10;
        break;
      case '十一月':
        month = 11;
        break;
      case '十二月':
        month = 12;
    }
    capacityStatus = [];
    dayPre = 0;
    $('.dayNumber').each(function(i) {
      var applying, date, day, remaining;
      day = parseInt($(this).text());
      if (i === 0 && day !== 1) {
        month--;
      } else {
        if (day < dayPre) {
          month++;
        }
      }
      dayPre = day;
      if ($(this).parent().children().length > 1) {
        date = new Date();
        date.setMonth(month - 1);
        date.setDate(day);
        remaining = $(this).parent().find('#eventscalendar_Label1_0').html().split('<br>')[1].split(':')[1];
        applying = $(this).parent().find('#eventscalendar_Label1_0').html().split('<br>')[2].split(':')[1];
        return capacityStatus.push({
          'date': date,
          'remaining': remaining,
          'applying': applying,
          'waiting': null
        });
      }
    });
    return console.log(capacityStatus);
  };

}).call(this);
