// Generated by CoffeeScript 1.9.2
(function() {
  var app;

  app = angular.module('hutCrawler', []);

  app.controller('hutCrawlerCtrl', [
    '$scope', '$http', function($scope, $http) {
      $http.get('/api/hut').success(function(huts) {
        return $scope.huts = huts;
      }).error(function(e) {
        return console.log(e);
      });
      return $scope.hutNameClicked = function(hutName) {
        var day, hut, hutApplicableAll, hutApplicableInOneWeek, i, istatus, j, k, len, len1, ref, ref1, ref2, results, status;
        hutApplicableAll = [];
        hutApplicableInOneWeek = [];
        ref = $scope.huts;
        results = [];
        for (i = 0, len = ref.length; i < len; i++) {
          hut = ref[i];
          if (hut.nameZh === hutName) {
            ref1 = hut.capacityStatuses.status;
            for (istatus = j = 0, len1 = ref1.length; j < len1; istatus = ++j) {
              status = ref1[istatus];
              day = new Date(status.date).getDay();
              if (istatus === 0 && day !== 0) {
                for (k = 0, ref2 = day; 0 <= ref2 ? k < ref2 : k > ref2; 0 <= ref2 ? k++ : k--) {
                  hutApplicableInOneWeek.push({});
                }
              }
              hutApplicableInOneWeek.push(status);
              if (istatus === hut.capacityStatuses.status.length - 1 || day === 6) {
                hutApplicableAll.push(hutApplicableInOneWeek);
                hutApplicableInOneWeek = [];
              }
            }
            $scope.hutApplicableAll = hutApplicableAll;
            break;
          } else {
            results.push(void 0);
          }
        }
        return results;
      };
    }
  ]);

}).call(this);
