// Generated by CoffeeScript 1.8.0
(function() {
  var app;

  app = angular.module('hutCrawler', []);

  app.controller('hutCrawlerCtrl', [
    '$scope', '$http', function($scope, $http) {
      $http.get('/api/hut').success(function(huts) {
        return $scope.huts = huts;
      }).error(function(e) {
        return console.log(e);
      });
      return $scope.hutNameClicked = function(hutName) {
        var day, hut, hutApplicableAll, hutApplicableInOneWeek, istatus, status, _i, _j, _k, _len, _len1, _ref, _ref1, _results;
        hutApplicableAll = [];
        hutApplicableInOneWeek = [];
        _ref = $scope.huts;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          hut = _ref[_i];
          if (hut.nameZh === hutName) {
            _ref1 = hut.capacityStatuses.status;
            for (istatus = _j = 0, _len1 = _ref1.length; _j < _len1; istatus = ++_j) {
              status = _ref1[istatus];
              day = new Date(status.date).getDay();
              if (istatus === 0 && day !== 0) {
                for (_k = 0; 0 <= day ? _k < day : _k > day; 0 <= day ? _k++ : _k--) {
                  hutApplicableInOneWeek.push({});
                }
              }
              hutApplicableInOneWeek.push(status);
              if (istatus === hut.capacityStatuses.status.length - 1 || day === 6) {
                hutApplicableAll.push(hutApplicableInOneWeek);
                hutApplicableInOneWeek = [];
              }
            }
            $scope.hutApplicableAll = hutApplicableAll;
            break;
          } else {
            _results.push(void 0);
          }
        }
        return _results;
      };
    }
  ]);

}).call(this);
