// Generated by CoffeeScript 1.9.2
(function() {
  var apiKey, sendgrid;

  apiKey = 'ehyLECUeTeWzeCcbfRcQ2w';

  sendgrid = require('sendgrid')('namejoshua', 'jojo782011');

  module.exports = function(app) {
    app.get('/wedding', function(req, res) {
      return res.render('wedding/views/index');
    });
    app.get('/wedding/views/:name', function(req, res) {
      return res.render('wedding/views/' + req.params.name);
    });
    return app.get('/api/sendEmail', function(req, res) {
      var payload;
      console.log('yayaya');
      payload = {
        to: 'joshuayes@gmail.com',
        from: 'joshuayes@gmail.com',
        subject: 'Saying Hi',
        text: 'This is my first email through SendGrid'
      };
      return sendgrid.send(payload, function(err, json) {
        if (err) {
          console.error(err);
        }
        return console.log(json);
      });
    });
  };

}).call(this);
