// Generated by CoffeeScript 1.9.2
(function() {
  var data;

  data = ['h', 'e', 'l', 'l', 'o', 'w', 'o', 'r', 'l', 'd'];

  d3.select('body').selectAll('g').data(data).enter().append('p').text(function(d) {
    return d;
  });

}).call(this);
