// Generated by CoffeeScript 1.9.2
(function() {
  var async, capacityStatus, cheerio, ddlLocation, moment, parser, request, selectorRemaining, timeStartCrawling, urlAfterDraw, urlBeforeDraw;

  async = require('async');

  moment = require('moment');

  request = require('request');

  cheerio = require('cheerio');

  switch (2) {
    case 1:
      urlAfterDraw = 'https://mountain.ysnp.gov.tw/chinese/Location_Detail.aspx?pg=01&w=1&n=1005&s=1';
      urlBeforeDraw = 'https://mountain.ysnp.gov.tw/chinese/LocationAppIndex.aspx?pg=01&w=1&n=1003';
      selectorRemaining = 'span.style11 font';
      ddlLocation = 1;
      break;
    case 2:
      urlAfterDraw = 'https://mountain.ysnp.gov.tw/chinese/Location_Detail.aspx?pg=01&w=1&n=1005&s=136';
      urlBeforeDraw = 'https://mountain.ysnp.gov.tw/chinese/LocationAppIndex.aspx?pg=01&w=1&n=1003';
      selectorRemaining = 'span.style11 font';
      ddlLocation = 136;
      break;
    case 3:
      urlAfterDraw = 'https://mountain.ysnp.gov.tw/chinese/Location_Detail.aspx?pg=01&w=1&n=1005&s=136';
      urlBeforeDraw = 'https://mountain.ysnp.gov.tw/chinese/LocationAppIndex.aspx?pg=01&w=1&n=1003';
      selectorRemaining = 'span.style12 font';
      ddlLocation = 136;
  }

  urlAfterDraw = 'https://mountain.ysnp.gov.tw/chinese/Location_Detail.aspx?pg=01&w=1&n=1005&s=1';

  urlBeforeDraw = 'https://mountain.ysnp.gov.tw/chinese/LocationAppIndex.aspx?pg=01&w=1&n=1003';

  timeStartCrawling = moment();

  capacityStatus = [];

  async.waterfall([
    function(cb) {
      return request(urlAfterDraw, function(err, res, body) {
        var $;
        $ = cheerio.load(body);
        return parser($, function() {
          return cb(null, $);
        });
      });
    }, function($, cb) {
      return request({
        'method': 'POST',
        'url': urlAfterDraw,
        'form': {
          '__EVENTTARGET': 'ctl00$ContentPlaceHolder1$CalendarReport',
          '__EVENTARGUMENT': $('table#ctl00_ContentPlaceHolder1_CalendarReport table tr td:nth-child(3) a').attr('href').substring(68, 68 + 5),
          '__VIEWSTATE': $('#__VIEWSTATE').val(),
          '__VIEWSTATEGENERATOR': $('#__VIEWSTATEGENERATOR').val(),
          '__EVENTVALIDATION': $('#__EVENTVALIDATION').val()
        }
      }, function(err, res, body) {
        return parser(cheerio.load(body), function() {
          return cb(null);
        });
      });
    }, function(cb) {
      return async.eachSeries([0, 1, 2, 3, 4], function(itmes, eachSerialFinished) {
        return request(urlBeforeDraw, function(err, res, body) {
          var $, date;
          $ = cheerio.load(body);
          date = moment().add(7 + capacityStatus.length, 'd');
          console.log(date.format());
          return request({
            'method': 'POST',
            'url': urlBeforeDraw,
            'form': {
              'ctl00_ContentPlaceHolder1_ToolkitScriptManager1_HiddenField': '',
              '__EVENTTARGET': '',
              '__EVENTARGUMENT': '',
              '__VIEWSTATE': $('#__VIEWSTATE').val(),
              '__VIEWSTATEGENERATOR': $('#__VIEWSTATEGENERATOR').val(),
              '__VIEWSTATEENCRYPTED': $('#__VIEWSTATEENCRYPTED').val(),
              '__EVENTVALIDATION': $('#__EVENTVALIDATION').val(),
              'ctl00$ContentPlaceHolder1$txtSDate': date.format('YYYY/MM/DD'),
              'ctl00$ContentPlaceHolder1$ddlLocation': ddlLocation,
              'ctl00$ContentPlaceHolder1$btnSearch.x': 6,
              'ctl00$ContentPlaceHolder1$btnSearch.y': 19,
              'ctl00$ContentPlaceHolder1$gvIndex$ctl13$ddlPager': 1
            }
          }, function(err, res, body) {
            var applying;
            $ = cheerio.load(body);
            applying = $('#ctl00_ContentPlaceHolder1_lblPeople').text();
            capacityStatus.push({
              'date': date.format(),
              'remaining': 92,
              'applying': applying,
              'isDrawn': false
            });
            return eachSerialFinished();
          });
        });
      }, function(err) {
        if (err) {
          return console.log(err);
        } else {
          return cb(null);
        }
      });
    }
  ], function(err, result) {
    console.log(capacityStatus);
    return console.log('time: ' + moment().diff(timeStartCrawling, 'seconds') + 's');
  });

  parser = function($, done) {
    return async.parallel({
      remainings: function(cb) {
        var remainings;
        remainings = [];
        $('span.style11 font').each(function(i) {
          return remainings.push(92 - $(this).text());
        });
        return cb(null, remainings);
      },
      applyings: function(cb) {
        var applyings;
        applyings = [];
        $('span.style14 font').each(function(i) {
          return applyings.push($(this).text());
        });
        return cb(null, applyings);
      }
    }, function(err, results) {
      var i, j, len, ref, remaining;
      ref = results.remainings;
      for (i = j = 0, len = ref.length; j < len; i = ++j) {
        remaining = ref[i];
        capacityStatus.push({
          'date': moment().add(7 + capacityStatus.length, 'day').format(),
          'remaining': remaining,
          'applying': results.applyings[i],
          'isDrawn': true
        });
      }
      return done();
    });
  };

}).call(this);
