// Generated by CoffeeScript 1.8.0
(function() {
  var async, collectionName, jsdom, jsdomScripts, moment, reCrawlTime, sheiPaParser, tarokoParser;

  async = require('async');

  jsdom = require('jsdom');

  moment = require('moment');

  collectionName = 'huts';

  reCrawlTime = 1 * 60 * 60 * 1000;

  jsdomScripts = ['http://code.jquery.com/jquery.js'];

  module.exports = {
    crawl: function(MongoClient, mongoServerUrl) {
      var crawlOnce;
      return (crawlOnce = function() {
        var dateCrawl;
        console.log('huts crawling');
        dateCrawl = moment().format();
        MongoClient.connect(mongoServerUrl, function(err, db) {
          var huts;
          huts = db.collection(collectionName);
          return huts.find().toArray(function(err, docs) {
            return async.each(docs, function(hut) {
              return jsdom.env(hut.url, jsdomScripts, function(err, window) {
                var $, capacityStatus;
                $ = window.$;
                capacityStatus = [];
                switch (hut.admin) {
                  case '雪霸國家公園':
                    capacityStatus = sheiPaParser($);
                    break;
                  case '太魯閣國家公園':
                    capacityStatus = tarokoParser($);
                }
                return huts.updateOne({
                  'nameZh': hut.nameZh
                }, {
                  $set: {
                    'capacityStatuses': {
                      'dateCrawl': dateCrawl,
                      'status': capacityStatus
                    }
                  }
                }, function(err, r) {
                  return console.log(err !== null ? err : 'success crawling ' + hut.nameZh);
                });
              });
            }, function(err) {
              return console.log('gg');
            });
          });
        });
        return setTimeout(crawlOnce, reCrawlTime);
      })();
    }
  };

  sheiPaParser = function($) {
    var capacityStatus;
    capacityStatus = [];
    $('table.TABLE2 tr').each(function(i) {
      if (i >= 2 && $(this).find('td:nth-child(1)').text() !== '') {
        return capacityStatus.push({
          'date': new Date($(this).find('td:nth-child(1)').text()),
          'remaining': $(this).find('td:nth-child(4)').text(),
          'applying': $(this).find('td:nth-child(5)').text(),
          'waiting': $(this).find('td:nth-child(6)').text()
        });
      }
    });
    return capacityStatus;
  };

  tarokoParser = function($) {
    var capacityStatus;
    capacityStatus = [];
    $('table tr').each(function(i) {
      var applying, applyingString;
      if (i >= 2) {
        applyingString = $(this).find('td:nth-child(2)').text();
        applying = applyingString === '------' ? 0 : applyingString.split('隊')[1].split('人')[0];
        return capacityStatus.push({
          'date': new Date($(this).find('td:nth-child(1)').text()),
          'remaining': $(this).find('td:nth-child(4)').text(),
          'applying': applying,
          'waiting': null
        });
      }
    });
    return capacityStatus;
  };

}).call(this);
