// Generated by CoffeeScript 1.9.2
(function() {
  var app;

  app = angular.module('twtrails', ['ngRoute']);

  app.config([
    '$routeProvider', function($routeProvider) {
      return $routeProvider.when('/twtrails', {
        templateUrl: 'views/index'
      }).otherwise({
        redirectTo: '/index'
      });
    }
  ]);

  app.controller('twtrailsCtrl', [
    '$scope', '$http', function($scope, $http, $sce) {
      return $http.get('../api/trail').success(function(result, statusCode) {
        console.log('ya');
        console.log(result);
        return $scope.points = result[0].points;
      }).error(function(e) {
        return console.log(e);
      });
    }
  ]);

}).call(this);
