// Generated by CoffeeScript 1.9.2
(function() {
  var app;

  app = angular.module('miro', ['ngRoute']);

  app.config([
    '$routeProvider', function($routeProvider) {
      return $routeProvider.when('/mrio', {
        templateUrl: 'views/index'
      }).otherwise({
        redirectTo: '/index'
      });
    }
  ]);

  app.controller('miroCtrl', [
    '$scope', '$http', '$sce', function($scope, $http, $sce) {
      var client;
      $scope.getReply = function() {
        $scope.progress = 'handling... plz wait...';
        $scope.reply = {};
        return $http({
          headers: {},
          method: 'GET',
          url: '/api/reply?question=' + $scope.question
        }).success(function(data, status, headers, config) {
          $scope.progress = '';
          data.youtube_embed_url = $sce.trustAsResourceUrl(data.youtube_embed_url);
          return $scope.reply = data;
        }).error(function(data, status, headers, config) {
          return $scope.progress = 'fail';
        });
      };
      ZeroClipboard.config({
        swfPath: "//cdnjs.cloudflare.com/ajax/libs/zeroclipboard/2.1.3/ZeroClipboard.swf"
      });
      client = new ZeroClipboard(document.getElementById('copy-button'));
      client.on('ready', function(readyEvent) {
        client.on('copy', function(event) {
          return event.clipboardData.setData('text/plain', 'Me: ' + $scope.question + '\nMiro: ' + $scope.reply.sentence + '\n' + $scope.reply.youtube_url);
        });
        return client.on('aftercopy', function(event) {
          return alert('Copied~!\n\nMe: ' + $scope.question + '\nMiro: ' + $scope.reply.sentence + '\n' + $scope.reply.youtube_url);
        });
      });
      return client.on('error', function() {
        alert('zeroclipboard swf load error');
        return ZeroClipboard.destroy();
      });
    }
  ]);

}).call(this);
