// Generated by CoffeeScript 1.9.2
(function() {
  var app;

  app = angular.module('comicCrawler', []);

  app.controller('comicCrawlerCtrl', [
    '$scope', function($scope) {
      var parser;
      $scope.pages = [];
      $scope.urlSubmitted = function() {
        return parser();
      };
      return parser = function() {
        var i, j, page, pages;
        pages = [];
        for (i = j = 1; j <= 25; i = ++j) {
          page = '000' + i;
          page = page.substr(-3, 3);
          pages.push($scope.url.replace('http://', 'https://') + page + '.jpg');
          console.log($scope.url + page + '.jpg');
        }
        return $scope.pages = pages;
      };
    }
  ]);

}).call(this);
