// Generated by CoffeeScript 1.9.2
(function() {
  var app;

  app = angular.module('gg', []);

  app.controller('ggCtrl', [
    '$scope', function($scope) {
      var i, j, page, pages;
      pages = [];
      for (i = j = 1; j <= 190; i = ++j) {
        page = '000' + i;
        page = page.substr(-3, 3);
        pages.push('http://99770.co/wp-content/uploads/a04cj84wj6uq04/1671/002//' + page + '.jpg');
      }
      return $scope.pages = pages;
    }
  ]);

}).call(this);
